language: node_js
node_js:
  - 15

before_install:
  - openssl aes-256-cbc -K $encrypted_e6cc0fb2b8da_key -iv $encrypted_e6cc0fb2b8da_iv -in travis.enc -out travis -d

install:
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy/deploy.sh
    on:
      branch: master
