language: node_js
node_js:
  - 15

install:
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy/deploy.sh
    on:
      branch: master

branches:
  only: 
    - master