language: node_js
node_js:
  - 15

before_install:
  - openssl aes-256-cbc -K $encrypted_e80721793c24_key -iv $encrypted_e80721793c24_iv -in private.enc -out private -d

install:
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy/deploy.sh
    on:
      branch: master
